(lang dune 3.3)

(name lwt_reporter_example)

(generate_opam_files true)

(license ISC)

(package
 (name lwt_reporter_example)
 (synopsis "example")
 (depends
  (cmdliner
   (= 1.1.1))
  (conf-libev
   (>= 4-12))
  (dune
   (>= 3.4.1))
  (logs
   (= 0.7.0))
  (lwt
   (>= 5.6.1))
   ))
